name: Publish Website to CPanel
on: push
jobs: 
  FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps: 
        - name: Deploy-Action
          uses: actions/checkout@v3
          
        - name: Sync files
          uses: SamKirkland/FTP-Deploy-Action@4.3.4
          with: 
            server: ${{secrets.FTP_SERVER}}
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
